### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by freakvencer** [ShotokanZH/MiWiFi_Mesh_Node_Adder#1]
I just get an error message when starting the script, what am i doing wrong?

ModuleNotFoundError: No module named 'requests'

**Comment by ShotokanZH** [comment]
Hi, the requests module is missing in your system. Just install it via:
`python3 -m pip3 install requests`

Beware: python 3.7 or higher is required (because of f-strings)

**Comment by freakvencer** [comment]
thanks, a lot.

**Comment by ShotokanZH** [comment]
You are welcome!
