### ISSUE TITLE
Not able to type in Master Password

### ISSUE THREAD

**Issue by powl69** [ShotokanZH/MiWiFi_Mesh_Node_Adder#2]
Hi there,
first of all thanks for all the effort you put in - i am very impressed of this easy work-around and appreciate it a lot!
After typing in the IP of the Master Router i get asked for the password. Unfortunately i am not able to type anything in, it wont take any commands other then me hitting "enter". I want to type in the password, but it just wont recognize it. As if my keyboard is not plugged in.. lol :)

is there any solution for that possibly?

Thanks a lot!

Best regards
Paul

**Comment by ShotokanZH** [comment]
...it is a password field, it does not show the characters you type for security reasons... And no, there are no asterisks of sort, it's a basic password field, it's supposed to work like that...
