### ISSUE TITLE
Success message but nothing happens

### ISSUE THREAD

**Issue by gpressutto5** [ShotokanZH/MiWiFi_Mesh_Node_Adder#5]
After running the command it tells me to wait for it ro reboot but it won't reboot. So I did it manually, but it is still not working. The routers are ~1,5m apart and up to date.

```
MiWiFi Mesh Node Adder v1.0 by ShotokanZH
Master (online, configured) router address: 192.168.31.1
Master password:
Logging in..
Login: OK

Platform: R3600
AIoT scan status: ON

Asking master to scan for Xiaomi Wifi APs...
No AP detected! (Are the two devices close enough?)
You can continue, but it will probably fail.

Client (not configured) 5GHz mac address (AA:BB:CC:DD:EE:FF):9E:B2:00:22:BA:E00 Adding 9E:B2:00:22:BA:E0 as mesh node..
Node configured correctly! Wait for it to reboot.
```

**Comment by ShotokanZH** [comment]
Are the two devices using  Xiaomi firmware global 3.0.22?
Is the secondary / client device in factory reset state and not initialized?

**Comment by gpressutto5** [comment]
They run different versions, but both are on the most up-to-date version. I think the problem is I can't have the ax3600 as master and the ax3000 as satellite.
